In [5]:
import torch

In [22]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
z = y * y *  3
print(z)
out = z.mean()
print(out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [35]:
x = torch.ones(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1024., 1024., 1024.], grad_fn=<MulBackward0>)


In [36]:
v = torch.tensor([1,0,0], dtype=torch.float)
y.backward(v)

In [38]:
x.grad

tensor([1024.,    0.,    0.])